#!/usr/bin/env bash
set -eo pipefail

SCRIPT="$(readlink -f "${BASH_SOURCE[0]}")"
DIR="$(dirname ${SCRIPT})"
__HUGO__="${TAG:-$USER/hugo}"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

install_hugo() {
	local ctr=$1

	buildah run $ctr -- curl -Lo hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.tar.gz
	buildah run $ctr -- tar -xvf hugo.tar.gz
	buildah run $ctr -- mv hugo /usr/bin/hugo
}

build_hugo() {
	local ctr=$1
	local tag=${2:-$__HUGO__}
	source "${DIR}/../fedora/fedora"
	source "${DIR}/../vim/vim"

	container_from_fedora $ctr
	install_vim $ctr
	install_hugo $ctr
	buildah run $ctr -- dnf clean all
	buildah config --entrypoint '[ "/usr/bin/hugo" ]' --cmd 'help' $ctr
	buildah commit $ctr $tag
}

run_hugo() {
	local args=(
		--rm
		--interactive
		--tty
		--privileged
		--net host
		--volume $PWD:$PWD:rslave
		--workdir $PWD
	)

	podman run "${args[@]}" ${__HUGO__} "$@"
}

# If run as script
if ! $(return >/dev/null 2>&1); then
	case "$1" in
		build)
			ctr="hugo-working-container"
			TAG="${TAG:-$__HUGO__}"
			buildah rm $ctr >/dev/null 2>&1 || true
			build_hugo $ctr $TAG
			buildah rm $ctr >/dev/null 2>&1
			;;

		*)
			if ! buildah images ${__HUGO__} >/dev/null 2>&1; then
				echo "Hugo image does not exist, building..."
				$SCRIPT build
			fi
			run_hugo "$@"
			;;

	esac
fi
