#!/usr/bin/env bash
set -e
set -o pipefail

DEFAULT_TAG="${USER}/fedora"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

install_zsh() {
	local ctr=$1
	buildah run $ctr -- dnf install -y zsh git fzf ripgrep
	buildah copy $ctr $XDG_CONFIG_HOME/zsh /root/.config/zsh
	buildah config \
		--cmd "" \
		--entrypoint '[ "/usr/bin/zsh" ]' \
		--env ZDOTDIR="/root/.config/zsh" \
		--env FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules}/*" 2> /dev/null' \
		--label maintainer="David Zager <david.j.zager@gmail.com>" \
		$ctr
}

build_fedora() {
	local ctr=$1
	local tag="${2:-$DEFAULT_TAG}"

	buildah from --name $ctr --pull-always fedora
	buildah run $ctr -- dnf update -y
	install_zsh $ctr
	buildah commit $ctr $tag
}

container_from_fedora() {
	local ctr=$1
	local tag="${2:-$DEFAULT_TAG}"

	if buildah images $tag >/dev/null 2>&1; then
		buildah from --name $ctr $tag
	else
		build_fedora $ctr
	fi
}

# If run as script, then build it
if ! $(return >/dev/null 2>&1); then
	ctr="fedora-working-container"
	TAG="${TAG:-$DEFAULT_TAG}"
	buildah rm $ctr >/dev/null 2>&1 || true
	build_fedora $ctr $TAG
	buildah rm $ctr >/dev/null 2>&1
fi
